version: '3'

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
      - localstack
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - FLYWAY_COMMAND=flyway -url=jdbc:postgresql://db:5432/mydatabase -user=postgres -password=password -locations=filesystem:/app/flyway/sql -X migrate
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - S3_ENDPOINT_URL=http://localstack:4566

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data

  db:
    image: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
